# Generated by Django 5.0.4 on 2024-08-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=50)),
                ('stock_tonnage', models.CharField(max_length=50)),
                ('amount_paid', models.IntegerField(default=0)),
                ('buyer_names', models.CharField(max_length=50)),
                ('sales_agent_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_types', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_tonnage', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_cost', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_dealer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_branch_name', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_price', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
