# Generated by Django 5.0.6 on 2024-08-27 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0005_creditsale_remove_stocks_issued_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 3, 57, 31, 369984)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 3, 57, 31, 369984)),
        ),
    ]
