# Generated by Django 5.0.4 on 2024-09-03 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0008_alter_sale_stock_date_alter_stocks_stock_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='approval_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 1, 15, 57, 759118)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 1, 15, 57, 759118)),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
