# Generated by Django 5.0.4 on 2024-09-04 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0009_stocks_approval_status_alter_sale_stock_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='approval_status',
        ),
        migrations.AlterField(
            model_name='sale',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 14, 48, 6, 195027)),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 4, 14, 48, 6, 194032)),
        ),
    ]
